src/Entity/Contact.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class Contact
{
    /**
     * @var string
     * @Assert\Email()
     * @Assert\NotBlank()
     * @Assert\Length(max="255")
     */
    private $email;

    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(max="3000")
     */
    private $description;

    /**
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return Contact
     */
    public function setEmail(?string $email): Contact
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Contact
     */
    public function setDescription(?string $description): Contact
    {
        $this->description = $description;
        return $this;
    }


}

src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 * @UniqueEntity("email")
 */
class Person implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(max="255")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(max="255")
     */
    private $lastName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\NotNull()
     */
    private $birth;

    /**
     * @ORM\Column(type="string", length=65556, nullable=true)
     * @Assert\Length(max="65556")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Regex(pattern="/^[0-9 ]*$/",message="This value can only contain digits")
     * @Assert\Length(max="255")
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="string", length=255, unique=true, nullable=false)
     * @Assert\Email()
     * @Assert\NotBlank()
     * @Assert\Length(max="255")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(max="255")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     * @Assert\Length(max="1000")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max="255")
     */
    private $cv;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max="255")
     * @Assert\Regex(pattern="/^https:\/\/youtube.com\/channel\/.*$/")
     */
    private $youtube;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max="255")
     * @Assert\Regex(pattern="/^https:\/\/linkedin.com\/in\/.*$/")
     */
    private $linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max="255")
     * @Assert\Regex(pattern="/^https:\/\/github.com\/.*$/")
     */
    private $github;

    /**
     * @ORM\OneToMany(targetEntity="Skill", mappedBy="createdBy")
     */
    private $skills;

    /**
     * @ORM\OneToMany(targetEntity="Experience", mappedBy="createdBy")
     */
    private $experiences;

    /**
     * @ORM\ManyToMany(targetEntity="Project", mappedBy="followers")
     */
    private $followedProjects;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Project", inversedBy="visibleBy")
     */
    private $visibleProjects;

    /**
     * @ORM\OneToMany(targetEntity="Project", mappedBy="createdBy")
     */
    private $createdProjects;

    /**
     * @ORM\OneToMany(targetEntity="Link", mappedBy="createdBy")
     */
    private $createdLinks;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     * @Assert\NotNull()
     */
    private $isAdmin;




    public function __construct()
    {
        $this->setBirth(new \DateTime("now"));
        $this->followedProjects = new ArrayCollection();
        $this->setIsAdmin(false);
        $this->skills = new ArrayCollection();
        $this->experiences = new ArrayCollection();
        $this->createdProjects = new ArrayCollection();
        $this->createdLinks = new ArrayCollection();
        $this->visibleProjects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = ucfirst($firstName);

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = ucfirst($lastName);

        return $this;
    }

    public function getBirth(): ?\DateTimeInterface
    {
        return $this->birth;
    }

    public function setBirth(\DateTimeInterface $birth): self
    {
        $this->birth = $birth;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture()
    {
        return ($this->picture ?? $_ENV['DEFAULT_PROFILE_PICTURE']);
    }

    public function setPicture($picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getYoutube(): ?string
    {
        return $this->youtube;
    }

    public function setYoutube(?string $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->github;
    }

    public function setGithub(?string $github): self
    {
        $this->github = $github;

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getFollowedProjects(): Collection
    {
        return $this->followedProjects;
    }

    public function addFollowedProject(Project $project): self
    {
        if (!$this->followedProjects->contains($project)) {
            $this->followedProjects[] = $project;
            $project->addFollower($this);
        }

        return $this;
    }

    public function removeFollowedProject(Project $project): self
    {
        if ($this->followedProjects->contains($project)) {
            $this->followedProjects->removeElement($project);
            $project->removeFollower($this);
        }

        return $this;
    }


    /**
     * @return Collection|Skill[]
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills[] = $skill;
            $skill->setCreatedBy($this);
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        if ($this->skills->contains($skill)) {
            $this->skills->removeElement($skill);
            // set the owning side to null (unless already changed)
            if ($skill->getCreatedBy() === $this) {
                $skill->setCreatedBy(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getEmail();
    }

    /**
     * @return Collection|Experience[]
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experience $experience): self
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences[] = $experience;
            $experience->setCreatedBy($this);
        }

        return $this;
    }

    public function removeExperience(Experience $experience): self
    {
        if ($this->experiences->contains($experience)) {
            $this->experiences->removeElement($experience);
            // set the owning side to null (unless already changed)
            if ($experience->getCreatedBy() === $this) {
                $experience->setCreatedBy(null);
            }
        }

        return $this;
    }


    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->getEmail();
    }

    /**
     * @inheritDoc
     */
    public function setPassword(?string $password): self
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        if ($this->getIsAdmin())
            return ["ROLE_USER", "ROLE_ADMIN"];
        else
            return ["ROLE_USER"];
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getNbProjectsCreatedAndFollowed(): int
    {
        return $this->getFollowedProjects()->count() + $this->getCreatedProjects()->count();
    }

    /**
     * @return Collection|Project[]
     */
    public function getCreatedProjects(): Collection
    {
        return $this->createdProjects;
    }

    public function addCreatedProject(Project $createdProject): self
    {
        if (!$this->createdProjects->contains($createdProject)) {
            $this->createdProjects[] = $createdProject;
            $createdProject->setCreatedBy($this);
        }

        return $this;
    }

src/Entity/ProjectStatistic.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectStatisticRepository")
 */
class ProjectStatistic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=false, length=255)
     * @Assert\NotBlank()
     * @Assert\Range(max="255")
     */
    private $value;

    /**
     * @ORM\Column(type="datetime", nullable=false, type="datetime")
     * @Assert\NotNull()
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="Project", inversedBy="statistics", cascade={"persist"})
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $project;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function incrementValue(): self
    {
        $this->value = (int)$this->value + 1;

        return $this;
    }

    public function getDate(): \DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getProject(): Project
    {
        return $this->project;
    }

    public function setProject(Project $project): self
    {
        $this->project = $project;

        return $this;
    }

}

src/Form/PersonType.php
<?php

namespace App\Form;

use App\Entity\Experience;
use App\Entity\Person;
use App\Entity\Project;
use App\Entity\Skill;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotNull;

class PersonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName', TextType::class, [
                'label' => 'form.name.first'
            ])
            ->add('lastName', TextType::class, [
                'label' => 'form.name.last'
            ])
            ->add('birth', TextType::class, [
                'mapped' => false,
                'label' => 'form.birth',
                'attr' => [
                    'class' => 'date mb-3',
                ], 'constraints' => [
                    new NotNull()
                ]
            ])
            ->add('description', TextareaType::class, [
                'required' => false,
                'label' => 'form.description.description',
            ])
            ->add('phoneNumber', TelType::class, [
                'label' => 'form.phone_number'
            ])
            ->add('email', EmailType::class, [
                'translation_domain' => false,

            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'required' => true,
                'first_options' => [
                    'label' => 'form.password.password',
                ],
                'second_options' => [
                    'label' => 'form.password.confirm'
                ],
            ])
            ->add('picture', FileType::class, [
                'label' => false,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'placeholder' => 'form.picture.profile.info'
                ],
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'form.picture.profile.error'
                    ])
                ]
            ])
            ->add('cv', FileType::class, [
                'label' => false,
                'translation_domain' => false,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'placeholder' => 'CV... (pdf)'
                ],
                'constraints' => [
                    new File([
                        'maxSize' => '8192k',
                        'mimeTypes' => [
                            'application/pdf',
                        ],
                        'mimeTypesMessage' => 'cv.error'
                    ])
                ]
            ])
            ->add('youtube', TextType::class, [
                'translation_domain' => false,
            ])
            ->add('linkedin', TextType::class, [
                'translation_domain' => false,

            ])
            ->add('github', TextType::class, [
                'translation_domain' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Person::class,
        ]);
    }
}

templates/manager/entity/person/show.html.twig
{% set id = person.id %}
{% extends 'manager/base/_show.html.twig' %}

{% block title %}{{ person.firstName }} {{ person.lastName }}{% endblock %}

{% block header %}
    {{ parent() }}
    <div class="col order-1">{{ include ('manager/button/_portfolio.html.twig', {'label' : 'portfolio','person_id' : person.id }) }}</div>
{% endblock %}
{% block content %}


    <div class="row border my-4 p-3">
        <div class="col-3 align-self-center">
            <img class="img-fluid rounded shadow border" alt="Profile picture"
                 src="{{ asset('uploads/images/profiles/' ~ person.picture) }}"/>
        </div>
        <div class="col">
            <div class="row">
                <div class="col-12"><h3>{{ person.firstName }} {{ person.lastName }}</h3></div>
                <div class="col-12 p-2"><p>{{ person.description|default('No description...') }}</p></div>
                <div class="col-12 align-self-end table-responsive-xl">
                    <table class="table table-bordered">
                        <thead class="thead-light">
                        <tr class="text-nowrap">
                            <th scope="col">Email</th>
                            <th scope="col">{{ 'form.phone_number'|trans }}</th>
                            <th scope="col">{{ 'form.birth'|trans }}</th>
                            <th scope="col">{{ 'social_media'|trans }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="table-light">
                            <td style="overflow-wrap: break-word; max-width: 310px;">{{ person.email }}</td>
                            <td class="text-nowrap">
                                <span id="phoneNumber">{{ person.phoneNumber }}</span>
                                <input type="hidden" id="person_phoneNumber" value="{{ person.phoneNumber }}"/>
                            </td>
                            <td>{{ person.birth|date('d/m/Y') }}</td>
                            <td>
                                <a href="{{ person.youtube }}">Youtube</a>,
                                <a href="{{ person.github }}">Github</a>,
                                <a href="{{ person.linkedin }}">Linkedin</a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% if formChangePassword is not null %}
        {{ form_start(formChangePassword) }}
        <button id="button-change-password-show" type="button" class="btn btn-primary font-weight-bold"
                data-toggle="modal"
                data-target="#modal-change-password">{{ 'form.password.change'|trans }}</button>

        <div class="modal fade" id="modal-change-password" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title mx-auto">{{ 'form.password.change'|trans }}</h5>
                    </div>
                    <div class="modal-body">
                        <div id="content-password-edit" class="alert mb-2" role="alert">
                            <span></span>
                        </div>
                        <div class="row align-items-center justify-content-around">
                            <div class="col-12">
                                {{ form_row(formChangePassword.currentPassword) }}
                            </div>
                            {% for password in formChangePassword.newPassword %}
                                <div class="col-12">
                                    {{ form_row(password) }}
                                </div>
                            {% endfor %}

                        </div>

                    </div>
                    <div class="modal-footer">
                        <div class="col-6 d-flex justify-content-center">
                            {{ include('manager/button/_.html.twig',{ 'button_type' : 'button','data_dismiss': 'modal', 'logo' : 'close-circle', 'label' : 'action.close'|trans, 'color': 'danger'}) }}
                        </div>
                        <div class="col-6 d-flex justify-content-center">
                            {{ include('manager/button/_.html.twig',{ 'button_type' : 'submit', 'logo' : 'save', 'label' : 'action.save.changes'|trans, 'color': 'success','button_id' : 'button-change-password'}) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{ form_end(formChangePassword) }}
    {% endif %}
    {% if person.nbProjectsCreatedAndFollowed > 0 %}
        <div class="text-center">
            <h1>All times views of followed projects : {{ totalViewsProjectsFollowed }}</h1>
            <h1>All times views of created projects : {{ totalViewsProjectsCreated }}</h1>
            <h1>All times views of all projects : {{ totalViewsProjectsAll }}</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-12">
                <canvas id="myChart"></canvas>
            </div>
        </div>
    {% else %}
        <div class="text-center">No created and followed projects...</div>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.5.10/cleave.min.js"
            crossorigin="anonymous"></script>
    <script src="{{ asset('js/cleave/phone-type-formater.fr.js') }}"></script>
    <script>
        new Cleave($('#person_phoneNumber'), {
            phone: true,
            phoneRegionCode: 'FR'
        });

        $('#phoneNumber').text($('#person_phoneNumber').val());
        {% if formChangePassword is not null %}
        $(`#content-password-edit`).hide();

        let loading = `{{ include('manager/loading/_circle.html.twig') }}`
        let cooldown = 1500;
        let delay = 800;
        let requestDone = true;
        let cooldownReady = true;
        let resultPassword = $(`#content-password-edit`);
        let currentColor = '';
        $(document).ready(function () {
            $('#button-change-password-show').click(function () {
                setTimeout(function () {
                    $('#change_password_currentPassword').focus();
                }, 50)
            })

            $('#button-change-password').click(function (event) {
                event.preventDefault();
                if (cooldownReady && requestDone)
                    $.ajax({
                        url: '{{ path('person_edit_password',{'id' : person.id }) }}',
                        method: 'POST',
                        datatype: 'json',
                        beforeSend: function () {
                            resultPassword.fadeOut(200)
                            cooldownReady = false;
                            requestDone = false;
                            setTimeout(function () {
                                cooldownReady = true;
                            }, cooldown);
                            $("#button-change-password ion-icon:first").hide(300, function () {
                                $("#button-change-password").prepend(loading)
                            })
                        },
                        data: {
                            'currentPassword': $('#change_password_currentPassword').val(),
                            'newPassword_first': $('#change_password_newPassword_first').val(),
                            'newPassword_second': $('#change_password_newPassword_second').val(),
                            '_token': $("#change_password__token").val(),
                        },
                        statusCode: {
                            200: function (content) {
                                setTimeout(function () {
                                    displayMessage('alert-success', content.message)
                                }, delay)
                            },
                            400: function (content) {
                                setTimeout(function () {
                                    displayMessage('alert-danger', content.responseJSON.message)
                                }, delay);
                            },
                            403: function (content) {
                                setTimeout(function () {
                                    displayMessage('alert-warning', content.responseJSON.message)
                                }, delay);
                            }
                        }
                    }).always(function () {
                        requestDone = true;
                    });

                function displayMessage(color, message) {
                    resultPassword.removeClass(currentColor)
                    currentColor = color;
                    resultPassword.addClass(color)
                    $("#content-password-edit").fadeIn(300).find('span:first').text(message);
                    $("#button-change-password svg:first").hide(200, function () {
                        $("#button-change-password ion-icon:first").show()
                        $(this).remove()
                    })
                }
            });

            $("#button-close-password-edit").click(function () {
                resultPassword.fadeOut();
            });
        });
        {% endif %}
    </script>
    <script>
        let ctx = document.getElementById('myChart').getContext('2d');

        function getRandomInt(max) {
            return Math.floor(Math.random() * Math.floor(max));
        }

        function getRandomColor() {
            let letters = '0123456789ABCDEF';
            let color = '#';
            for (var i = 0; i < 6; i++) {
                color += letters[Math.floor(Math.random() * 16)];
            }
            return color;
        }

        let config = {
            type: 'bar',
            data: {
                labels: [{% for statistics in statisticsProjectsCreated|first %}'{{ statistics.date|date('m/Y') }}',{% endfor %}],
                datasets: [
                        {% for statistics in statisticsProjectsCreated %}{
                        label: "{{ statistics[0].project.name }}",
                        backgroundColor: `rgba(${getRandomInt(255)}, ${getRandomInt(255)}, ${getRandomInt(255)}, 0.7)`,
                        borderColor: `rgba(${getRandomInt(255)}, ${getRandomInt(255)}, ${getRandomInt(255)}, 0.7)`,
                        data: [{% for statistic in statistics %}'{{ statistic.value }}',{% endfor %}],
                        fill: false,
                    },{% endfor %}],
            },
            options: {
                elements: {
                    line: {
                        tension: 0.4
                    },
                },
                responsive: true,
                title: {
                    display: true,
                    text: 'Views of created projects'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: false,
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Views'
                        }, ticks: {
                            min: 0,
                        }
                    }]
                }
            }
        };

        new Chart(ctx, config)
    </script>

{% endblock %}